export interface SceneTimelineItem {
  sceneId: string;
  chapterId: string;
  chapterTitle: string;
  name: string;
  voiceover: string;
  durationSeconds: number;
  durationFrames: number;
  startFrame: number;
  endFrame: number;
  takeType: 'KEYFRAME_DOSSIER' | 'CINEMATIC_TAKE';
  integratedText?: string;
  audioFile?: string;
}

export const EPISODE_05_TOTAL_FRAMES = 11971;
export const EPISODE_05_TOTAL_SECONDS = 398.86;

export const EPISODE_05_TIMELINE: SceneTimelineItem[] = [
  {
    "sceneId": "OOL_001",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "O Gatilho da Frenagem",
    "voiceover": "Você está dirigindo à noite em uma rodovia deserta. De repente, uma placa surge na escuridão e você pisa no freio por puro reflexo.",
    "durationSeconds": 8.48,
    "durationFrames": 254,
    "startFrame": 0,
    "endFrame": 254,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_001.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_002",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "O Clarão Vermelho",
    "voiceover": "Muitos motoristas já sentiram aquele frio na espinha ao ver um clarão vermelho no retrovisor, acreditando que uma câmera no poste calculou sua velocidade.",
    "durationSeconds": 9.45,
    "durationFrames": 284,
    "startFrame": 254,
    "endFrame": 538,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_002.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_003",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "O Mito do Olho Eletrônico",
    "voiceover": "Mas a maioria das pessoas não sabe que a câmera montada no poste é cega para a sua velocidade. Ela não mede absolutamente nada.",
    "durationSeconds": 8.11,
    "durationFrames": 243,
    "startFrame": 538,
    "endFrame": 781,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_003.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_004",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "O Registro Instantâneo",
    "voiceover": "A câmera é apenas a testemunha final de um julgamento físico que durou menos de um décimo de segundo.",
    "durationSeconds": 5.69,
    "durationFrames": 171,
    "startFrame": 781,
    "endFrame": 952,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_004.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "FLASH // DISPARO A 1/10.000s"
  },
  {
    "sceneId": "OOL_005",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "A Revelação da Pista",
    "voiceover": "O verdadeiro radar não está em cima do poste. Ele está enterrado sob as suas rodas, esculpido dentro do próprio asfalto.",
    "durationSeconds": 7.73,
    "durationFrames": 232,
    "startFrame": 952,
    "endFrame": 1184,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_005.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_006",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "O Corte de Diamante",
    "voiceover": "Para transformar a rodovia em um sensor gigante, equipes de engenharia usam serras com ponta de diamante para rasgar o pavimento.",
    "durationSeconds": 7.46,
    "durationFrames": 224,
    "startFrame": 1184,
    "endFrame": 1408,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_006.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_007",
    "chapterId": "CH01",
    "chapterTitle": "O Clarão na Escuridão & O Mito da Câmera",
    "name": "O Nascimento do Sensor",
    "voiceover": "Dentro dessas fendas, operários instalam uma armadilha eletromagnética invisível que nunca dorme.",
    "durationSeconds": 6.29,
    "durationFrames": 189,
    "startFrame": 1408,
    "endFrame": 1597,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_007.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_008",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "A Geometria dos Três Laços",
    "voiceover": "Em cada faixa monitorada, a engenharia desenha um padrão geométrico rigoroso: três laços retangulares perfeitamente alinhados.",
    "durationSeconds": 9.03,
    "durationFrames": 271,
    "startFrame": 1597,
    "endFrame": 1868,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_008.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_009",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "A Distância Inegociável",
    "voiceover": "A distância entre a borda do primeiro laço e a borda do segundo é fixada em exatamente três metros, com tolerância milimétrica.",
    "durationSeconds": 7.87,
    "durationFrames": 236,
    "startFrame": 1868,
    "endFrame": 2104,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_009.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "3 METROS // DISTÂNCIA PADRÃO"
  },
  {
    "sceneId": "OOL_010",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "O Laço Indutivo por Dentro",
    "voiceover": "Cada laço é composto por voltas contínuas de fio de cobre, formando uma bobina indutiva conectada a um circuito ressonante.",
    "durationSeconds": 7.59,
    "durationFrames": 228,
    "startFrame": 2104,
    "endFrame": 2332,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_010.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_011",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "A Frequência de Silêncio",
    "voiceover": "Uma corrente alternada de alta frequência percorre o laço constantemente, criando um campo eletromagnético invisível acima do asfalto.",
    "durationSeconds": 9.64,
    "durationFrames": 289,
    "startFrame": 2332,
    "endFrame": 2621,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_011.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_012",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "O Equilíbrio Invisível",
    "voiceover": "Enquanto nenhum veículo passa, a indutância do circuito permanece estável. O sistema está em repouso calibrado.",
    "durationSeconds": 6.71,
    "durationFrames": 201,
    "startFrame": 2621,
    "endFrame": 2822,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_012.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_013",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "O Sensor Piezoelétrico",
    "voiceover": "Em radares de pesagem e classificação, uma lâmina de quartzo piezoelétrico é adicionada para medir a deformação mecânica do peso dos eixos.",
    "durationSeconds": 9.08,
    "durationFrames": 272,
    "startFrame": 2822,
    "endFrame": 3094,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_013.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_014",
    "chapterId": "CH02",
    "chapterTitle": "O Mapa do Asfalto: Laços Indutivos & Cristais de Quartzo",
    "name": "O Gabinete Blindado",
    "voiceover": "Toda essa malha subterrânea converge para um gabinete blindado à beira da estrada, onde um computador industrial de tempo real processa os sinais.",
    "durationSeconds": 9.22,
    "durationFrames": 277,
    "startFrame": 3094,
    "endFrame": 3371,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_014.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_015",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "A Chegada da Massa Metálica",
    "voiceover": "No instante em que a carcaça de aço do seu carro entra sobre o primeiro laço, a massa metálica perturba as linhas de fluxo magnético.",
    "durationSeconds": 8.52,
    "durationFrames": 256,
    "startFrame": 3371,
    "endFrame": 3627,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_015.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "ΔT = 60.000 µs"
  },
  {
    "sceneId": "OOL_016",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "A Corrente de Foucault",
    "voiceover": "O metal do chassi induz correntes parasitas que alteram instantaneamente a indutância total da bobina enterrada.",
    "durationSeconds": 7.04,
    "durationFrames": 211,
    "startFrame": 3627,
    "endFrame": 3838,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_016.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_017",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "O Disparo do Cronômetro",
    "voiceover": "A queda de indutância gera um pulso elétrico agudo. O microcontrolador registra o evento no instante T-zero e inicia o cronômetro.",
    "durationSeconds": 9.55,
    "durationFrames": 287,
    "startFrame": 3838,
    "endFrame": 4125,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_017.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_018",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "A Travessia dos Três Metros",
    "voiceover": "O carro continua se deslocando pela pista, cobrindo o intervalo fixo de três metros até o segundo laço indutivo.",
    "durationSeconds": 6.94,
    "durationFrames": 208,
    "startFrame": 4125,
    "endFrame": 4333,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_018.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_019",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "O Segundo Impacto Magnético",
    "voiceover": "Ao atingir o segundo laço, uma nova perturbação é detectada e o cronômetro é travado no instante T-um.",
    "durationSeconds": 7.5,
    "durationFrames": 225,
    "startFrame": 4333,
    "endFrame": 4558,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_019.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_020",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "A Diferença de Tempo",
    "voiceover": "A máquina agora possui dois dados irrefutáveis: a distância física conhecida e o tempo exato decorrido entre os dois pulsos.",
    "durationSeconds": 7.97,
    "durationFrames": 239,
    "startFrame": 4558,
    "endFrame": 4797,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_020.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_021",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "A Matemática Pura",
    "voiceover": "Em menos de um milissegundo, a equação fundamental da física é executada: velocidade é igual à distância dividida pelo tempo.",
    "durationSeconds": 8.57,
    "durationFrames": 257,
    "startFrame": 4797,
    "endFrame": 5054,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_021.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_022",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "A Prova da Velocidade",
    "voiceover": "Se o veículo levou noventa milissegundos para cruzar três metros, sua velocidade calculada foi de cento e vinte quilômetros por hora.",
    "durationSeconds": 7.69,
    "durationFrames": 231,
    "startFrame": 5054,
    "endFrame": 5285,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_022.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "V = ΔS / ΔT"
  },
  {
    "sceneId": "OOL_023",
    "chapterId": "CH03",
    "chapterTitle": "A Passagem do Veículo: O Cálculo em Microssegundos",
    "name": "O Terceiro Laço de Validação",
    "voiceover": "Mas a lei exige segurança total: um terceiro laço realiza a mesma medição para cruzar os resultados e eliminar falsos positivos.",
    "durationSeconds": 8.01,
    "durationFrames": 240,
    "startFrame": 5285,
    "endFrame": 5525,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_023.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_024",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "A Ordem de Disparo",
    "voiceover": "Se a velocidade apurada ultrapassar o limite da via, o processador envia um comando elétrico imediato para o topo do poste.",
    "durationSeconds": 7.32,
    "durationFrames": 220,
    "startFrame": 5525,
    "endFrame": 5745,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_024.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_025",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "O Obturador Global",
    "voiceover": "A câmera aciona um obturador global ultra-rápido, capaz de congelar qualquer movimento sem a distorção típica de celulares.",
    "durationSeconds": 7.87,
    "durationFrames": 236,
    "startFrame": 5745,
    "endFrame": 5981,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_025.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_026",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "O Iluminador Infravermelho",
    "voiceover": "Simultaneamente, um iluminador infravermelho invisível ao olho humano banha o veículo com luz estroboscópica.",
    "durationSeconds": 7.64,
    "durationFrames": 229,
    "startFrame": 5981,
    "endFrame": 6210,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_026.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_027",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "O Segredo da Placa",
    "voiceover": "É aqui que a ótica entra em ação: as placas automotivas são cobertas por uma película retrorrefletiva microprismática.",
    "durationSeconds": 8.15,
    "durationFrames": 245,
    "startFrame": 6210,
    "endFrame": 6455,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_027.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_028",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "O Retorno Direto da Luz",
    "voiceover": "Em vez de espalhar a luz para os lados, a placa devolve quase cem por cento dos fótons diretamente para a lente da câmera.",
    "durationSeconds": 7.73,
    "durationFrames": 232,
    "startFrame": 6455,
    "endFrame": 6687,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_028.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_029",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "A Imagem de Alto Contraste",
    "voiceover": "Mesmo a duzentos quilômetros por hora e sob tempestade, a placa aparece cristalina, como se o carro estivesse perfeitamente parado.",
    "durationSeconds": 9.5,
    "durationFrames": 285,
    "startFrame": 6687,
    "endFrame": 6972,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_029.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_030",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "A Rede Neural de OCR",
    "voiceover": "O algoritmo de reconhecimento óptico de caracteres segmenta cada letra e número em microssegundos com noventa e nove por cento de precisão.",
    "durationSeconds": 9.55,
    "durationFrames": 287,
    "startFrame": 6972,
    "endFrame": 7259,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_030.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "OCR // LEITURA DE PLACA"
  },
  {
    "sceneId": "OOL_031",
    "chapterId": "CH04",
    "chapterTitle": "O Olho da Lei: Câmera Estroboscópica, OCR & Película 3M",
    "name": "O Pacote de Evidência",
    "voiceover": "Um pacote digital criptografado é criado na hora, contendo a foto panorâmica, o recorte da placa, a telemetria dos sensores e a hora exata.",
    "durationSeconds": 9.5,
    "durationFrames": 285,
    "startFrame": 7259,
    "endFrame": 7544,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_031.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_032",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "A Temperatura do Pavimento",
    "voiceover": "Mas a física da rodovia é implacável: o asfalto não é um laboratório controlado. No verão brasileiro, o pavimento atinge mais de sessenta graus.",
    "durationSeconds": 10.55,
    "durationFrames": 317,
    "startFrame": 7544,
    "endFrame": 7861,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_032.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_033",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "A Dilatação do Asfalto",
    "voiceover": "Com o calor extremo e o peso constante de caminhões de quarenta toneladas, o pavimento se deforma e as ranhuras podem se mover milímetros.",
    "durationSeconds": 8.8,
    "durationFrames": 264,
    "startFrame": 7861,
    "endFrame": 8125,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_033.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_034",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "O Risco do Milímetro",
    "voiceover": "Se a distância real entre os laços mudar alguns centímetros, o cálculo de velocidade será matematicamente corrompido.",
    "durationSeconds": 7.79,
    "durationFrames": 234,
    "startFrame": 8125,
    "endFrame": 8359,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_034.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_035",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "A Autocalibração Térmica",
    "voiceover": "Por isso, os equipamentos modernos monitoram a impedância de base e compensam a variação térmica do cobre continuamente.",
    "durationSeconds": 8.22,
    "durationFrames": 247,
    "startFrame": 8359,
    "endFrame": 8606,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_035.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_036",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "A Auditoria do INMETRO",
    "voiceover": "Todo radar em operação no país precisa ser inspecionado periodicamente pelo INMETRO com veículos padrão de alta precisão.",
    "durationSeconds": 7.91,
    "durationFrames": 237,
    "startFrame": 8606,
    "endFrame": 8843,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_036.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_037",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "O Teste da Pista",
    "voiceover": "Dez passagens em velocidades diferentes são realizadas. Se o erro for superior a um por cento, o radar é lacrado e desativado.",
    "durationSeconds": 9.52,
    "durationFrames": 286,
    "startFrame": 8843,
    "endFrame": 9129,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_037.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_038",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "A Margem Legal de 7 km/h",
    "voiceover": "É exatamente para cobrir essas microvariações da física do asfalto que a lei aplica a famosa tolerância de sete quilômetros por hora.",
    "durationSeconds": 8.65,
    "durationFrames": 260,
    "startFrame": 9129,
    "endFrame": 9389,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_038.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "MARGEM INMETRO: ±7 KM/H"
  },
  {
    "sceneId": "OOL_039",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "O Descarte Automático",
    "voiceover": "Se dois veículos cruzarem os laços ao mesmo tempo ou se houver oscilação elétrica, o sistema descarta o registro para evitar multas indevidas.",
    "durationSeconds": 9.49,
    "durationFrames": 285,
    "startFrame": 9389,
    "endFrame": 9674,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_039.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_040",
    "chapterId": "CH05",
    "chapterTitle": "O Limite do INMETRO & O Ponto de Falha no Asfalto",
    "name": "O Lacre Criptográfico",
    "voiceover": "As infrações válidas recebem uma assinatura digital criptográfica que impede qualquer adulteração humana posterior.",
    "durationSeconds": 7.67,
    "durationFrames": 230,
    "startFrame": 9674,
    "endFrame": 9904,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_040.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_041",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "A Rede Oculta da Cidade",
    "voiceover": "Nas grandes capitais, milhares desses sensores operam dia e noite, monitorando milhões de veículos a cada minuto.",
    "durationSeconds": 8.05,
    "durationFrames": 242,
    "startFrame": 9904,
    "endFrame": 10146,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_041.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_042",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "Muito Além das Multas",
    "voiceover": "Eles não servem apenas para fiscalizar: os laços indutivos são os sensores que alimentam os semáforos inteligentes e controlam o fluxo urbano.",
    "durationSeconds": 9.28,
    "durationFrames": 278,
    "startFrame": 10146,
    "endFrame": 10424,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_042.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_043",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "A Engenharia da Precisão",
    "voiceover": "Uma combinação improvável de corte de pedra, eletromagnetismo do século dezenove e redes neurais modernas.",
    "durationSeconds": 7.65,
    "durationFrames": 230,
    "startFrame": 10424,
    "endFrame": 10654,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_043.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_044",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "A Ilusão da Câmera",
    "voiceover": "Da próxima vez que você passar por um radar na rodovia e olhar para o poste com desconfiança...",
    "durationSeconds": 6.28,
    "durationFrames": 188,
    "startFrame": 10654,
    "endFrame": 10842,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_044.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_045",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "O Olhar para o Chão",
    "voiceover": "...lembre-se de que a máquina que mediu o seu tempo não estava olhando para você lá de cima.",
    "durationSeconds": 5.68,
    "durationFrames": 170,
    "startFrame": 10842,
    "endFrame": 11012,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_045.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_046",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "A Máquina Subterrânea",
    "voiceover": "Ela estava debaixo das suas rodas, contando microssegundos no silêncio escuro do pavimento.",
    "durationSeconds": 6.45,
    "durationFrames": 194,
    "startFrame": 11012,
    "endFrame": 11206,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_046.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_047",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "O Relógio do Asfalto",
    "voiceover": "Porque no mundo invisível da infraestrutura, a velocidade nada mais é do que uma fração de tempo congelada na matéria.",
    "durationSeconds": 7.79,
    "durationFrames": 234,
    "startFrame": 11206,
    "endFrame": 11440,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_047.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_048",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "A Curiosidade Revelada",
    "voiceover": "Isso é o que acontece depois que você acelera, freia e segue viagem.",
    "durationSeconds": 5.32,
    "durationFrames": 160,
    "startFrame": 11440,
    "endFrame": 11600,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_048.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_049",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "O Chamado à Compreensão",
    "voiceover": "Descubra a engenharia oculta por trás de tudo o que sustenta a sua rotina.",
    "durationSeconds": 5.39,
    "durationFrames": 162,
    "startFrame": 11600,
    "endFrame": 11762,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_049.mp3",
    "takeType": "CINEMATIC_TAKE"
  },
  {
    "sceneId": "OOL_050",
    "chapterId": "CH06",
    "chapterTitle": "A Conclusão Causal: O Relógio de Asfalto",
    "name": "A Assinatura do Canal",
    "voiceover": "O Outro Lado. Investigar. Revelar. Compreender.",
    "durationSeconds": 6.97,
    "durationFrames": 209,
    "startFrame": 11762,
    "endFrame": 11971,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP05-RADAR-ASFALTO\\audio_scenes\\OOL_050.mp3",
    "takeType": "KEYFRAME_DOSSIER",
    "integratedText": "INVESTIGAR. REVELAR. COMPREENDER."
  }
];
