export interface SceneTimelineItem {
  sceneId: string;
  chapterId: string;
  chapterTitle: string;
  name: string;
  voiceover: string;
  durationSeconds: number;
  durationFrames: number;
  startFrame: number;
  endFrame: number;
  audioFile?: string;
}

export const EPISODE_04_TOTAL_FRAMES = 13939;
export const EPISODE_04_TOTAL_SECONDS = 464.63;

export const EPISODE_04_TIMELINE: SceneTimelineItem[] = [
  {
    "sceneId": "OOL_001",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "O Mito da Localização",
    "voiceover": "Quando você abre o mapa no celular para pedir um carro ou conferir uma rota, quase todo mundo imagina que um satélite no espaço está olhando para você.",
    "durationSeconds": 9.63,
    "durationFrames": 289,
    "startFrame": 0,
    "endFrame": 289,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_001.mp3"
  },
  {
    "sceneId": "OOL_002",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "A Realidade Invertida",
    "voiceover": "Mas a realidade é exatamente o oposto: os satélites de GPS não fazem ideia de onde você está. Eles não recebem nada. Eles apenas gritam as horas.",
    "durationSeconds": 9.54,
    "durationFrames": 286,
    "startFrame": 289,
    "endFrame": 575,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_002.mp3"
  },
  {
    "sceneId": "OOL_003",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "O Experimento Mental do Desligamento",
    "voiceover": "Se a constelação inteira de satélites fosse desligada agora, os carros continuariam andando pelas ruas com mapas salvos na memória.",
    "durationSeconds": 8.29,
    "durationFrames": 249,
    "startFrame": 575,
    "endFrame": 824,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_003.mp3"
  },
  {
    "sceneId": "OOL_004",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "O Colapso Invisível",
    "voiceover": "Porém, em menos de dez minutos, o sistema bancário global travaria, transações de Pix seriam rejeitadas e as antenas de telefonia celular entrariam em colapso.",
    "durationSeconds": 10.47,
    "durationFrames": 314,
    "startFrame": 824,
    "endFrame": 1138,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_004.mp3"
  },
  {
    "sceneId": "OOL_005",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "A Fundação da Civilização",
    "voiceover": "Porque o GPS não é um sistema de localização. Ele é o relógio mestre sobre o qual toda a economia digital do planeta foi construída.",
    "durationSeconds": 8.33,
    "durationFrames": 250,
    "startFrame": 1138,
    "endFrame": 1388,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_005.mp3"
  },
  {
    "sceneId": "OOL_006",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "O Nanossegundo",
    "voiceover": "Cada fração de segundo da vida moderna está ancorada em uma unidade invisível: o nanossegundo, a bilionésima parte de um segundo.",
    "durationSeconds": 9.87,
    "durationFrames": 296,
    "startFrame": 1388,
    "endFrame": 1684,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_006.mp3"
  },
  {
    "sceneId": "OOL_007",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "A Conexão Oculta",
    "voiceover": "E a história desse mecanismo começa a mais de vinte mil quilômetros de altitude, no vácuo congelante da órbita da Terra.",
    "durationSeconds": 7.17,
    "durationFrames": 215,
    "startFrame": 1684,
    "endFrame": 1899,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_007.mp3"
  },
  {
    "sceneId": "OOL_008",
    "chapterId": "CH01",
    "chapterTitle": "O Mito do Mapa & O Clique Invisível",
    "name": "O Início da Viagem",
    "voiceover": "Onde trinta e um satélites executam silenciosamente a coreografia mais precisa já concebida pela engenharia humana.",
    "durationSeconds": 6.85,
    "durationFrames": 206,
    "startFrame": 1899,
    "endFrame": 2105,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_008.mp3"
  },
  {
    "sceneId": "OOL_009",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "A Órbita Média",
    "voiceover": "A constelação GPS opera em órbita média a vinte mil e duzentos quilômetros de altitude, completando duas voltas completas no planeta a cada dia.",
    "durationSeconds": 9.26,
    "durationFrames": 278,
    "startFrame": 2105,
    "endFrame": 2383,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_009.mp3"
  },
  {
    "sceneId": "OOL_010",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "O Coração Atômico",
    "voiceover": "No coração de cada satélite existem relógios atômicos de Césio e Rubídio que não usam engrenagens nem cristais de quartzo comuns.",
    "durationSeconds": 8.71,
    "durationFrames": 261,
    "startFrame": 2383,
    "endFrame": 2644,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_010.mp3"
  },
  {
    "sceneId": "OOL_011",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "A Frequência Imutável",
    "voiceover": "Eles medem a oscilação quântica do átomo de Césio cento e trinta e três, que vibra exatamente nove bilhões, cento e noventa e dois milhões de vezes por segundo.",
    "durationSeconds": 9.73,
    "durationFrames": 292,
    "startFrame": 2644,
    "endFrame": 2936,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_011.mp3"
  },
  {
    "sceneId": "OOL_012",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "A Mensagem de Rádio",
    "voiceover": "O satélite não envia sua posição geográfica. Ele transmite apenas um pacote de rádio dizendo a sua hora atômica exata e de qual satélite ela veio.",
    "durationSeconds": 9.31,
    "durationFrames": 279,
    "startFrame": 2936,
    "endFrame": 3215,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_012.mp3"
  },
  {
    "sceneId": "OOL_013",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "A Viagem na Velocidade da Luz",
    "voiceover": "Esse sinal viaja pelo vácuo na velocidade da luz: quase trezentos mil quilômetros por segundo, levando cerca de sessenta e sete milissegundos para tocar a superfície.",
    "durationSeconds": 10.7,
    "durationFrames": 321,
    "startFrame": 3215,
    "endFrame": 3536,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_013.mp3"
  },
  {
    "sceneId": "OOL_014",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "A Matemática da Distância",
    "voiceover": "Ao medir a diferença infinitesimal entre a hora em que o sinal saiu do satélite e a hora em que chegou, o seu aparelho calcula a distância exata.",
    "durationSeconds": 8.8,
    "durationFrames": 264,
    "startFrame": 3536,
    "endFrame": 3800,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_014.mp3"
  },
  {
    "sceneId": "OOL_015",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "Trilateração Esférica",
    "voiceover": "Com quatro satélites visíveis simultaneamente, as quatro esferas temporais se cruzam em um único ponto geométrico no espaço e no tempo.",
    "durationSeconds": 8.38,
    "durationFrames": 251,
    "startFrame": 3800,
    "endFrame": 4051,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_015.mp3"
  },
  {
    "sceneId": "OOL_016",
    "chapterId": "CH02",
    "chapterTitle": "A Constelação Orbital & A Física do Tempo",
    "name": "A Quarta Dimensão",
    "voiceover": "Três satélites calculam latitude, longitude e altitude. O quarto satélite existe exclusivamente para sincronizar o relógio barato do seu celular com os relógios atômicos orbitais.",
    "durationSeconds": 12.37,
    "durationFrames": 371,
    "startFrame": 4051,
    "endFrame": 4422,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_016.mp3"
  },
  {
    "sceneId": "OOL_017",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "A Chegada na Terra",
    "voiceover": "Na superfície, o sinal atômico que desce do espaço com a potência de uma lâmpada fraca é capturado por receptores industriais em telhados de centros de dados.",
    "durationSeconds": 10.01,
    "durationFrames": 300,
    "startFrame": 4422,
    "endFrame": 4722,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_017.mp3"
  },
  {
    "sceneId": "OOL_018",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "A Sala dos Servidores",
    "voiceover": "Dentro das salas de servidores da B3 em São Paulo e de Wall Street em Nova York, o tempo precisa ser absoluto.",
    "durationSeconds": 7.08,
    "durationFrames": 212,
    "startFrame": 4722,
    "endFrame": 4934,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_018.mp3"
  },
  {
    "sceneId": "OOL_019",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "Alta Frequência Financeira",
    "voiceover": "Robôs de negociação de alta frequência compram e vendem ativos em frações de microssegundos. Quem chega primeiro, lucra.",
    "durationSeconds": 7.78,
    "durationFrames": 233,
    "startFrame": 4934,
    "endFrame": 5167,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_019.mp3"
  },
  {
    "sceneId": "OOL_020",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "O Perigo da Duplicidade",
    "voiceover": "Se dois bancos tiverem uma discrepância de apenas um microssegundo em seus relógios, é impossível saber qual ordem entrou primeiro no mercado.",
    "durationSeconds": 8.29,
    "durationFrames": 249,
    "startFrame": 5167,
    "endFrame": 5416,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_020.mp3"
  },
  {
    "sceneId": "OOL_021",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "O Carimbo do Pix",
    "voiceover": "O mesmo princípio rege o Pix: cada transação precisa de um carimbo temporal inviolável para garantir que o dinheiro não foi gasto duas vezes simultaneamente.",
    "durationSeconds": 9.68,
    "durationFrames": 290,
    "startFrame": 5416,
    "endFrame": 5706,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_021.mp3"
  },
  {
    "sceneId": "OOL_022",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "O Protocolo PTP",
    "voiceover": "Esse alinhamento é feito pelo protocolo de tempo de precisão, que distribui o sinal do GPS para cada processador com tolerância menor que dez nanossegundos.",
    "durationSeconds": 9.12,
    "durationFrames": 274,
    "startFrame": 5706,
    "endFrame": 5980,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_022.mp3"
  },
  {
    "sceneId": "OOL_023",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "As Antenas 5G",
    "voiceover": "E nas telecomunicações, as antenas de cinco G dependem dessa mesma sincronia para enviar múltiplos feixes de dados sem que um feixe destrua o outro por interferência.",
    "durationSeconds": 10.33,
    "durationFrames": 310,
    "startFrame": 5980,
    "endFrame": 6290,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_023.mp3"
  },
  {
    "sceneId": "OOL_024",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "A Teia Invisível",
    "voiceover": "Sem que ninguém perceba, toda a infraestrutura física de pagamentos, energia e internet pulsa no mesmo compasso vindo do espaço.",
    "durationSeconds": 8.1,
    "durationFrames": 243,
    "startFrame": 6290,
    "endFrame": 6533,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_024.mp3"
  },
  {
    "sceneId": "OOL_025",
    "chapterId": "CH03",
    "chapterTitle": "A Jornada do Nanossegundo: Dos Satélites a Wall Street e à Faria Lima",
    "name": "O Inimigo Oculto",
    "voiceover": "Mas manter esse compasso perfeito esbarra em um dos maiores obstáculos da física fundamental: as leis do próprio universo.",
    "durationSeconds": 8.1,
    "durationFrames": 243,
    "startFrame": 6533,
    "endFrame": 6776,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_025.mp3"
  },
  {
    "sceneId": "OOL_026",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "O Paradoxo do Tempo",
    "voiceover": "Quando o primeiro satélite experimental foi lançado, muitos engenheiros duvidavam que a teoria da relatividade de Einstein afetaria sistemas práticos de engenharia.",
    "durationSeconds": 10.1,
    "durationFrames": 303,
    "startFrame": 6776,
    "endFrame": 7079,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_026.mp3"
  },
  {
    "sceneId": "OOL_027",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "A Relatividade Especial",
    "voiceover": "Pela Relatividade Especial, corpos em alta velocidade experimentam o tempo mais devagar. A quatorze mil quilômetros por hora, o relógio do satélite perde sete microssegundos por dia.",
    "durationSeconds": 12.47,
    "durationFrames": 374,
    "startFrame": 7079,
    "endFrame": 7453,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_027.mp3"
  },
  {
    "sceneId": "OOL_028",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "A Relatividade Geral",
    "voiceover": "Porém, pela Relatividade Geral, a gravidade desacelera o tempo. A vinte mil quilômetros de altitude, a gravidade é quatro vezes mais fraca, e o tempo no satélite passa mais rápido.",
    "durationSeconds": 11.58,
    "durationFrames": 347,
    "startFrame": 7453,
    "endFrame": 7800,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_028.mp3"
  },
  {
    "sceneId": "OOL_029",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "O Saldo Relativístico",
    "voiceover": "Somando os dois efeitos, o relógio atômico no espaço anda exatamente trinta e oito vírgula sete microssegundos mais rápido a cada vinte e quatro horas.",
    "durationSeconds": 10.56,
    "durationFrames": 317,
    "startFrame": 7800,
    "endFrame": 8117,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_029.mp3"
  },
  {
    "sceneId": "OOL_030",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "A Escala do Desastre",
    "voiceover": "Trinta e oito microssegundos parece nada para um ser humano. Mas na velocidade da luz, trinta e oito microssegundos equivalem a mais de onze quilômetros de erro a cada dia.",
    "durationSeconds": 11.26,
    "durationFrames": 338,
    "startFrame": 8117,
    "endFrame": 8455,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_030.mp3"
  },
  {
    "sceneId": "OOL_031",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "O Colapso do Posicionamento",
    "voiceover": "Em uma semana, o seu celular erraria a sua posição por quase cem quilômetros, tornando qualquer rota ou pouso por instrumentos completamente impossível.",
    "durationSeconds": 9.31,
    "durationFrames": 279,
    "startFrame": 8455,
    "endFrame": 8734,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_031.mp3"
  },
  {
    "sceneId": "OOL_032",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "O Colapso Financeiro",
    "voiceover": "E nos bancos, transações financeiras com carimbos futuros ou passados seriam sumariamente descartadas por firewalls de auditoria.",
    "durationSeconds": 8.33,
    "durationFrames": 250,
    "startFrame": 8734,
    "endFrame": 8984,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_032.mp3"
  },
  {
    "sceneId": "OOL_033",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "A Solução dos Físicos",
    "voiceover": "Para resolver isso, os cientistas programaram os sintetizadores dos satélites para vibrar ligeiramente mais devagar na fábrica, compensando a relatividade com perfeição milimétrica.",
    "durationSeconds": 11.26,
    "durationFrames": 338,
    "startFrame": 8984,
    "endFrame": 9322,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_033.mp3"
  },
  {
    "sceneId": "OOL_034",
    "chapterId": "CH04",
    "chapterTitle": "O Gargalo de Einstein: O Erro de 38 Microssegundos que Quebraria o Planeta",
    "name": "A Fragilidade do Ajuste",
    "voiceover": "Mas a física não é o único desafio. Manter esse castelo de cartas de pé exige um exército de estações terrestres corrigindo o sistema vinte e quatro horas por dia.",
    "durationSeconds": 11.31,
    "durationFrames": 339,
    "startFrame": 9322,
    "endFrame": 9661,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_034.mp3"
  },
  {
    "sceneId": "OOL_035",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "A Sala de Controle Mestre",
    "voiceover": "No interior de uma base fortificada no Colorado, o Segundo Esquadrão de Operações Espaciais monitora cada pulso dos trinta e um satélites.",
    "durationSeconds": 8.8,
    "durationFrames": 264,
    "startFrame": 9661,
    "endFrame": 9925,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_035.mp3"
  },
  {
    "sceneId": "OOL_036",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "A Correção Diária",
    "voiceover": "Pelo menos uma vez ao dia, estações de controle enviam comandos de correção para ajustar o arrasto atmosférico e o desvio residual dos relógios atômicos.",
    "durationSeconds": 9.36,
    "durationFrames": 281,
    "startFrame": 9925,
    "endFrame": 10206,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_036.mp3"
  },
  {
    "sceneId": "OOL_037",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "A Hora Legal Brasileira",
    "voiceover": "No Brasil, o Observatório Nacional mantém os padrões primários da Hora Legal Brasileira, comparando dados com laboratórios de metrologia em todo o mundo.",
    "durationSeconds": 9.68,
    "durationFrames": 290,
    "startFrame": 10206,
    "endFrame": 10496,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_037.mp3"
  },
  {
    "sceneId": "OOL_038",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "A Ameaça do Jamming",
    "voiceover": "No entanto, o sinal do GPS chega à Terra tão fraco quanto a luz de uma vela vista a quilômetros de distância, tornando-o vulnerável a interferência proposital.",
    "durationSeconds": 10.15,
    "durationFrames": 305,
    "startFrame": 10496,
    "endFrame": 10801,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_038.mp3"
  },
  {
    "sceneId": "OOL_039",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "O Ataque de Spoofing",
    "voiceover": "Com transmissores de spoofing, atacantes conseguem transmitir sinais falsificados mais fortes, enganando navios e aviões sobre sua localização e sobre a própria hora certa.",
    "durationSeconds": 9.96,
    "durationFrames": 299,
    "startFrame": 10801,
    "endFrame": 11100,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_039.mp3"
  },
  {
    "sceneId": "OOL_040",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "A Corrida por Alternativas",
    "voiceover": "Por essa razão, bancos centrais e setores de defesa estão construindo redes terrestres de fibra óptica com relógios atômicos locais para não dependerem exclusivamente do céu.",
    "durationSeconds": 10.15,
    "durationFrames": 305,
    "startFrame": 11100,
    "endFrame": 11405,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_040.mp3"
  },
  {
    "sceneId": "OOL_041",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "A Rede Resiliente",
    "voiceover": "Camadas de backup que garantem que, mesmo em caso de tempestades solares severas ou conflitos geopolíticos, o carimbo temporal continue existindo.",
    "durationSeconds": 10.15,
    "durationFrames": 305,
    "startFrame": 11405,
    "endFrame": 11710,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_041.mp3"
  },
  {
    "sceneId": "OOL_042",
    "chapterId": "CH05",
    "chapterTitle": "A Sala de Controle & As Redes Terrestres de Redundância",
    "name": "O Ponto de Virada",
    "voiceover": "Revelando a verdadeira dimensão de uma infraestrutura que opera em silêncio absoluto abaixo dos nossos olhos.",
    "durationSeconds": 6.71,
    "durationFrames": 201,
    "startFrame": 11710,
    "endFrame": 11911,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_042.mp3"
  },
  {
    "sceneId": "OOL_043",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "A Ilusão do Concreto",
    "voiceover": "Nós nos acostumamos a pensar que a civilização moderna é feita de pontes de aço, edifícios de concreto e cabos de fibra óptica.",
    "durationSeconds": 8.19,
    "durationFrames": 246,
    "startFrame": 11911,
    "endFrame": 12157,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_043.mp3"
  },
  {
    "sceneId": "OOL_044",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "A Realidade Imaterial",
    "voiceover": "Mas a verdade física é que todo esse ecossistema material depende de uma abstração invisível transmitida por trinta e um pontos brilhantes no céu.",
    "durationSeconds": 8.98,
    "durationFrames": 269,
    "startFrame": 12157,
    "endFrame": 12426,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_044.mp3"
  },
  {
    "sceneId": "OOL_045",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "O Preço da Sincronia",
    "voiceover": "Para que milhões de pessoas possam pagar um café, enviar uma mensagem ou se deslocar em segurança ao mesmo tempo, todos os relógios precisam concordar a cada bilionésimo de segundo.",
    "durationSeconds": 12.42,
    "durationFrames": 373,
    "startFrame": 12426,
    "endFrame": 12799,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_045.mp3"
  },
  {
    "sceneId": "OOL_046",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "O Triunfo de Einstein",
    "voiceover": "O mesmo cálculo que parecia uma teoria abstrata no início do século vinte é hoje a única coisa que impede o seu banco de falhar.",
    "durationSeconds": 8.15,
    "durationFrames": 245,
    "startFrame": 12799,
    "endFrame": 13044,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_046.mp3"
  },
  {
    "sceneId": "OOL_047",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "A Fragilidade do Tempo",
    "voiceover": "O tempo não é um fluxo natural e garantido. No mundo digital, ele é uma engenharia frágil, cara e constantemente mantida à beira do descompasso.",
    "durationSeconds": 9.4,
    "durationFrames": 282,
    "startFrame": 13044,
    "endFrame": 13326,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_047.mp3"
  },
  {
    "sceneId": "OOL_048",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "O Próximo Clique",
    "voiceover": "Da próxima vez que você abrir um aplicativo ou confirmar um pagamento em um segundo, lembre-se do que está acontecendo acima da sua cabeça.",
    "durationSeconds": 8.57,
    "durationFrames": 257,
    "startFrame": 13326,
    "endFrame": 13583,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_048.mp3"
  },
  {
    "sceneId": "OOL_049",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "A Máquina Cósmica",
    "voiceover": "Trinta e um relógios atômicos no vácuo, corrigindo a gravidade de Einstein para que o mundo na Terra não pare de girar.",
    "durationSeconds": 6.8,
    "durationFrames": 204,
    "startFrame": 13583,
    "endFrame": 13787,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_049.mp3"
  },
  {
    "sceneId": "OOL_050",
    "chapterId": "CH06",
    "chapterTitle": "Conclusão Causal: A Infraestrutura Mais Frágil da Terra",
    "name": "Encerramento O Outro Lado",
    "voiceover": "Este é o outro lado do tempo. O sistema invisível que sustenta a sua realidade.",
    "durationSeconds": 5.08,
    "durationFrames": 152,
    "startFrame": 13787,
    "endFrame": 13939,
    "audioFile": "C:\\Users\\brend\\OneDrive\\Desktop\\PROJETO 30K ATE 27\\02 - O OUTRO LADO\\AUTOMACAO - O OUTRO LADO\\runs\\OOL-EP04-GPS-TEMPO\\audio_scenes\\OOL_050.mp3"
  }
];

export const EPISODE_04_SCENES = EPISODE_04_TIMELINE;
