// Generated by HSL Sound Design Agent - AudioPlan v1.0.0
// Video ID: OOL-EP01-PIX | Total Frames: 10848 | FPS: 30
import React from 'react';
import {Audio, Sequence, staticFile, interpolate} from 'remotion';

function dbToLinear(db: number): number {
  return Math.pow(10, db / 20);
}

export const RemotionCinematicAudioBed: React.FC = () => {
  return (
    <>
      {/* ======================================================== */}
      {/* SCENE: OOL_001 (suspense | digital_banking) */}
      {/* ======================================================== */}
      <Sequence from={0} durationInFrames={330}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={330}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_01 | mid) */} 
        <Sequence from={30} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_02.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_click_02 | mid) */} 
        <Sequence from={60} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_03.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (impact | ominous_boom | low) */} 
        <Sequence from={120} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_001 (triple_calcar) */}
        <Sequence from={315} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={320} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={330} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_002 (suspense | datacenter_night) */}
      {/* ======================================================== */}
      <Sequence from={330} durationInFrames={208}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={208}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_04.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_002 (triple_calcar) */}
        <Sequence from={193} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_02.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={198} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_02.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={208} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_02.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_003 (epic | spi_core) */}
      {/* ======================================================== */}
      <Sequence from={538} durationInFrames={252}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={252}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_05.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_03 | mid) */} 
        <Sequence from={15} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_06.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={60} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_02.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_003 (triple_calcar) */}
        <Sequence from={237} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_03.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={242} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_03.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={252} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_03.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_004 (epic | spi_core) */}
      {/* ======================================================== */}
      <Sequence from={790} durationInFrames={368}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={368}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_07.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | tension_riser_01 | high) */} 
        <Sequence from={15} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_08.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={70} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_03.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_004 (triple_calcar) */}
        <Sequence from={353} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_04.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={358} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_04.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={368} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_04.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_005 (suspense | atomic_clock) */}
      {/* ======================================================== */}
      <Sequence from={1157} durationInFrames={234}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={234}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_09.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_04 | mid) */} 
        <Sequence from={10} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_10.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={50} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_04.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_005 (triple_calcar) */}
        <Sequence from={219} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_05.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={224} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_05.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={234} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_05.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_006 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1391} durationInFrames={244}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={244}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_11.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_02.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_006 (triple_calcar) */}
        <Sequence from={229} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={234} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={244} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_06.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_007 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1635} durationInFrames={230}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={230}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_12.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_03.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_007 (triple_calcar) */}
        <Sequence from={215} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={220} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={230} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_07.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_008 (action | fiber_optic_route) */}
      {/* ======================================================== */}
      <Sequence from={1864} durationInFrames={280}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/action/action_prelude_and_action.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={280}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_13.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (creative | scifi_laser_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | whoosh_swoosh_02 | high) */} 
        <Sequence from={45} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_008 (triple_calcar) */}
        <Sequence from={265} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={270} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={280} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_08.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_009 (suspense | protocol_inspector) */}
      {/* ======================================================== */}
      <Sequence from={2144} durationInFrames={259}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={259}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | scifi_laser_02 | mid) */} 
        <Sequence from={20} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_click_06 | mid) */} 
        <Sequence from={50} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_009 (triple_calcar) */}
        <Sequence from={244} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={249} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={259} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_09.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_010 (suspense | hsm_vault) */}
      {/* ======================================================== */}
      <Sequence from={2403} durationInFrames={223}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={223}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | scifi_laser_03 | mid) */} 
        <Sequence from={15} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={55} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_05.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_010 (triple_calcar) */}
        <Sequence from={208} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={213} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={223} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_10.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_011 (action | fiber_route) */}
      {/* ======================================================== */}
      <Sequence from={2625} durationInFrames={278}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/action/action_prelude_and_action.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={278}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_03 | high) */} 
        <Sequence from={0} durationInFrames={20}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_04.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_011 (triple_calcar) */}
        <Sequence from={263} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={268} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={278} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_11.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_012 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={2904} durationInFrames={210}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={210}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_05.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_012 (triple_calcar) */}
        <Sequence from={195} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={200} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={210} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_12.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_013 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3114} durationInFrames={210}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={210}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_013 (triple_calcar) */}
        <Sequence from={195} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={200} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={210} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_13.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_014 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3324} durationInFrames={291}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={291}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_014 (triple_calcar) */}
        <Sequence from={276} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={281} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={291} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_14.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_015 (epic | dict_directory) */}
      {/* ======================================================== */}
      <Sequence from={3614} durationInFrames={259}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={259}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (impact | ominous_boom | low) */} 
        <Sequence from={25} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_015 (triple_calcar) */}
        <Sequence from={244} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={249} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={259} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_15.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_016 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3873} durationInFrames={358}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={358}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_016 (triple_calcar) */}
        <Sequence from={343} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={348} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={358} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_16.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_017 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4231} durationInFrames={228}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={228}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_017 (triple_calcar) */}
        <Sequence from={213} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={218} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={228} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_17.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_018 (epic | settlement_core) */}
      {/* ======================================================== */}
      <Sequence from={4459} durationInFrames={312}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={312}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (impact | ominous_boom | low) */} 
        <Sequence from={30} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_018 (triple_calcar) */}
        <Sequence from={297} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={302} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={312} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_18.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_019 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4771} durationInFrames={226}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={226}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_019 (triple_calcar) */}
        <Sequence from={211} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={216} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={226} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_19.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_020 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4997} durationInFrames={253}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={253}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_020 (triple_calcar) */}
        <Sequence from={238} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={243} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={253} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_20.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_021 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={5250} durationInFrames={233}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={233}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_021 (triple_calcar) */}
        <Sequence from={218} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={223} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={233} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_21.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_022 (suspense | security_shield) */}
      {/* ======================================================== */}
      <Sequence from={5483} durationInFrames={199}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={199}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | scifi_laser_01 | mid) */} 
        <Sequence from={20} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_022 (triple_calcar) */}
        <Sequence from={184} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={189} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={199} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_22.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_023 (suspense | ai_engine) */}
      {/* ======================================================== */}
      <Sequence from={5682} durationInFrames={237}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={237}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_07 | mid) */} 
        <Sequence from={25} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_023 (triple_calcar) */}
        <Sequence from={222} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={227} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={237} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_23.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_024 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={5918} durationInFrames={288}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={288}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_024 (triple_calcar) */}
        <Sequence from={273} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={278} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={288} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_24.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_025 (suspense | med_protocol) */}
      {/* ======================================================== */}
      <Sequence from={6207} durationInFrames={277}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={277}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | foley_door_01 | mid) */} 
        <Sequence from={20} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/doors/foley_door_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_025 (triple_calcar) */}
        <Sequence from={262} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={267} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={277} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_25.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_026 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6483} durationInFrames={270}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={270}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_026 (triple_calcar) */}
        <Sequence from={255} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={260} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={270} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_26.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_027 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6754} durationInFrames={260}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={260}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_027 (triple_calcar) */}
        <Sequence from={245} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={250} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={260} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_27.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_028 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7014} durationInFrames={156}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={156}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_028 (triple_calcar) */}
        <Sequence from={141} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={146} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={156} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_28.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_029 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7170} durationInFrames={210}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={210}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_029 (triple_calcar) */}
        <Sequence from={195} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={200} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={210} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_29.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_030 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7380} durationInFrames={219}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={219}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_030 (triple_calcar) */}
        <Sequence from={204} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={209} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={219} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_30.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_031 (action | fiber_cut_emergency) */}
      {/* ======================================================== */}
      <Sequence from={7598} durationInFrames={269}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/action/action_prelude_and_action.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={269}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (impact | ominous_boom | low) */} 
        <Sequence from={20} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_031 (triple_calcar) */}
        <Sequence from={254} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={259} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={269} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_31.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_032 (action | auto_reroute) */}
      {/* ======================================================== */}
      <Sequence from={7867} durationInFrames={287}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/action/action_prelude_and_action.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={287}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | whoosh_swoosh_04 | high) */} 
        <Sequence from={15} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_032 (triple_calcar) */}
        <Sequence from={272} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={277} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={287} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_32.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_033 (suspense | power_station) */}
      {/* ======================================================== */}
      <Sequence from={8154} durationInFrames={310}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={310}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | foley_vehicle_01 | mid) */} 
        <Sequence from={20} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_033 (triple_calcar) */}
        <Sequence from={295} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={300} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={310} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_33.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_034 (epic | black_friday_stress) */}
      {/* ======================================================== */}
      <Sequence from={8464} durationInFrames={228}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={228}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | tension_riser_02 | high) */} 
        <Sequence from={25} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={80} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_034 (triple_calcar) */}
        <Sequence from={213} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={218} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={228} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_34.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_035 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={8693} durationInFrames={206}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={206}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_035 (triple_calcar) */}
        <Sequence from={191} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={196} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={206} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_35.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_036 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={8899} durationInFrames={277}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={277}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_036 (triple_calcar) */}
        <Sequence from={262} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={267} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={277} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_36.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_037 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={9175} durationInFrames={189}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={189}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_037 (triple_calcar) */}
        <Sequence from={174} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={179} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={189} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_37.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_038 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={9364} durationInFrames={260}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={260}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_038 (triple_calcar) */}
        <Sequence from={245} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={250} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={260} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_38.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_039 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={9624} durationInFrames={351}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={351}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_039 (triple_calcar) */}
        <Sequence from={336} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={341} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={351} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_39.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_040 (suspense | cinematic_documentary) */}
      {/* ======================================================== */}
      <Sequence from={9975} durationInFrames={386}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={386}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_040 (triple_calcar) */}
        <Sequence from={371} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={376} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={386} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_40.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_041 (epic | national_sovereignty) */}
      {/* ======================================================== */}
      <Sequence from={10361} durationInFrames={308}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={308}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (impact | ominous_boom | low) */} 
        <Sequence from={30} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_041 (triple_calcar) */}
        <Sequence from={293} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={298} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={308} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_41.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_042 (suspense | closing_curtain) */}
      {/* ======================================================== */}
      <Sequence from={10669} durationInFrames={179}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={179}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_05 | high) */} 
        <Sequence from={0} durationInFrames={20}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
      </Sequence>

    </>
  );
};
