// Generated by HSL Sound Design Agent - AudioPlan v1.0.0
// Video ID: OOL-EP02-CABOS | Total Frames: 8022 | FPS: 30
import React from 'react';
import {Audio, Sequence, staticFile, interpolate} from 'remotion';

function dbToLinear(db: number): number {
  return Math.pow(10, db / 20);
}

export const RemotionCinematicAudioBed: React.FC = () => {
  return (
    <>
      {/* ======================================================== */}
      {/* SCENE: OOL_001 (suspense | space_myth) */}
      {/* ======================================================== */}
      <Sequence from={0} durationInFrames={227}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={227}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_01 | mid) */} 
        <Sequence from={30} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_02.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_001 (triple_calcar) */}
        <Sequence from={212} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={217} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={227} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_002 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={227} durationInFrames={220}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={220}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_03.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_002 (triple_calcar) */}
        <Sequence from={205} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_02.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={210} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_02.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={220} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_02.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_003 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={447} durationInFrames={202}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={202}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_04.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_02.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_003 (triple_calcar) */}
        <Sequence from={187} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_03.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={192} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_03.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={202} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_03.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_004 (epic | laser_speed) */}
      {/* ======================================================== */}
      <Sequence from={649} durationInFrames={237}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={237}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_05.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_06.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={45} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_004 (triple_calcar) */}
        <Sequence from={222} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_04.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={227} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_04.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={237} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_04.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_005 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={886} durationInFrames={149}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={149}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_07.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_03.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_005 (triple_calcar) */}
        <Sequence from={134} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_05.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={139} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_05.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={149} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_05.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_006 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1035} durationInFrames={157}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={157}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_08.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_04.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_006 (triple_calcar) */}
        <Sequence from={142} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={147} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={157} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_06.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_007 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1192} durationInFrames={167}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={167}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_09.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_05.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_007 (triple_calcar) */}
        <Sequence from={152} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={157} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={167} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_07.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_008 (suspense | cable_reveal) */}
      {/* ======================================================== */}
      <Sequence from={1359} durationInFrames={205}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={205}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_10.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_02 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_click_02 | mid) */} 
        <Sequence from={40} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_11.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_008 (triple_calcar) */}
        <Sequence from={190} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={195} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={205} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_08.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_009 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1564} durationInFrames={209}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={209}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_12.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_009 (triple_calcar) */}
        <Sequence from={194} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={199} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={209} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_09.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_010 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1773} durationInFrames={166}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={166}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_13.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_010 (triple_calcar) */}
        <Sequence from={151} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={156} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={166} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_10.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_011 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={1939} durationInFrames={251}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={251}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_011 (triple_calcar) */}
        <Sequence from={236} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={241} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={251} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_11.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_012 (action | high_voltage) */}
      {/* ======================================================== */}
      <Sequence from={2190} durationInFrames={187}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/action/action_prelude_and_action.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={187}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | impact_boom_02 | low) */} 
        <Sequence from={30} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_012 (triple_calcar) */}
        <Sequence from={172} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={177} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={187} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_12.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_013 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={2377} durationInFrames={173}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={173}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_013 (triple_calcar) */}
        <Sequence from={158} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={163} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={173} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_13.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_014 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={2550} durationInFrames={222}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={222}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_014 (triple_calcar) */}
        <Sequence from={207} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={212} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={222} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_14.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_015 (suspense | deep_abyss) */}
      {/* ======================================================== */}
      <Sequence from={2772} durationInFrames={134}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={134}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_03 | mid) */} 
        <Sequence from={50} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_015 (triple_calcar) */}
        <Sequence from={119} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={124} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={134} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_15.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_016 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={2906} durationInFrames={206}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={206}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_016 (triple_calcar) */}
        <Sequence from={191} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={196} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={206} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_16.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_017 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3112} durationInFrames={215}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={215}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_017 (triple_calcar) */}
        <Sequence from={200} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={205} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={215} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_17.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_018 (epic | erbium_amplifier) */}
      {/* ======================================================== */}
      <Sequence from={3327} durationInFrames={196}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={196}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_03 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={35} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_02.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_018 (triple_calcar) */}
        <Sequence from={181} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={186} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={196} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_18.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_019 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3523} durationInFrames={184}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={184}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_019 (triple_calcar) */}
        <Sequence from={169} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={174} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={184} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_19.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_020 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3707} durationInFrames={223}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={223}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_020 (triple_calcar) */}
        <Sequence from={208} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={213} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={223} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_20.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_021 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={3930} durationInFrames={199}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={199}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_021 (triple_calcar) */}
        <Sequence from={184} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={189} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={199} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_21.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_022 (epic | cls_landing) */}
      {/* ======================================================== */}
      <Sequence from={4129} durationInFrames={215}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={215}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_04 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | loop_atmosphere_02 | mid) */} 
        <Sequence from={40} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* Transition: trans_022 (triple_calcar) */}
        <Sequence from={200} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={205} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={215} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_22.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_023 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4344} durationInFrames={177}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={177}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_023 (triple_calcar) */}
        <Sequence from={162} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={167} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={177} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_23.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_024 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4521} durationInFrames={209}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={209}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_024 (triple_calcar) */}
        <Sequence from={194} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={199} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={209} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_24.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_025 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4730} durationInFrames={199}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={199}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_025 (triple_calcar) */}
        <Sequence from={184} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={189} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={199} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_25.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_026 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={4929} durationInFrames={188}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={188}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_026 (triple_calcar) */}
        <Sequence from={173} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={178} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={188} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_26.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_027 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={5117} durationInFrames={177}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={177}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_027 (triple_calcar) */}
        <Sequence from={162} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={167} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={177} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_27.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_028 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={5294} durationInFrames={157}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={157}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_028 (triple_calcar) */}
        <Sequence from={142} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={147} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={157} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_28.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_029 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={5451} durationInFrames={145}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={145}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_029 (triple_calcar) */}
        <Sequence from={130} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={135} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={145} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_29.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_030 (action | anchor_strike) */}
      {/* ======================================================== */}
      <Sequence from={5596} durationInFrames={188}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/action/action_prelude_and_action.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={188}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_05 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={30} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_03.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_030 (triple_calcar) */}
        <Sequence from={173} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={178} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={188} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_30.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_031 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={5784} durationInFrames={171}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={171}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_031 (triple_calcar) */}
        <Sequence from={156} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={161} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={171} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_31.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_032 (suspense | bgp_failover) */}
      {/* ======================================================== */}
      <Sequence from={5955} durationInFrames={233}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={233}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | ui_click_04 | mid) */} 
        <Sequence from={0} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (impact | ominous_boom | low) */} 
        <Sequence from={25} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_04.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_032 (triple_calcar) */}
        <Sequence from={218} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={223} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={233} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_32.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_033 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6188} durationInFrames={222}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={222}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_033 (triple_calcar) */}
        <Sequence from={207} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={212} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={222} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_33.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_034 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6410} durationInFrames={210}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={210}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_034 (triple_calcar) */}
        <Sequence from={195} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={200} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={210} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_34.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_035 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6620} durationInFrames={185}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={185}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_035 (triple_calcar) */}
        <Sequence from={170} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={175} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={185} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_35.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_036 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6805} durationInFrames={160}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={160}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_036 (triple_calcar) */}
        <Sequence from={145} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={150} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={160} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_36.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_037 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={6965} durationInFrames={234}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={234}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_037 (triple_calcar) */}
        <Sequence from={219} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={224} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={234} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_37.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_038 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7199} durationInFrames={160}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={160}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_038 (triple_calcar) */}
        <Sequence from={145} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={150} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={160} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_38.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_039 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7359} durationInFrames={231}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={231}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_039 (triple_calcar) */}
        <Sequence from={216} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={221} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={231} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_39.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_040 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7590} durationInFrames={191}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={191}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_040 (triple_calcar) */}
        <Sequence from={176} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={181} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={191} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_40.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_041 (suspense | deep_ocean_documentary) */}
      {/* ======================================================== */}
      <Sequence from={7781} durationInFrames={123}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={123}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_01 | high) */} 
        <Sequence from={0} durationInFrames={15}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_041 (triple_calcar) */}
        <Sequence from={108} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={113} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={123} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_41.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: OOL_042 (suspense | closing_curtain) */}
      {/* ======================================================== */}
      <Sequence from={7904} durationInFrames={118}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={118}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (whoosh | whoosh_swoosh_05 | high) */} 
        <Sequence from={0} durationInFrames={20}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
      </Sequence>

    </>
  );
};
